[package]
name = "sota_client"
version = "0.2.0"
authors = ["Jerry Trieu <jerry@advancedtelematic.com>",
           "Philipp Millar <philipp@advancedtelematic.com>"]

[dependencies]
hyper = "*"
rustc-serialize = "*"
time = "*"
url = "*"
log = "*"
env_logger = "*"
rust-crypto = "*"

[dev-dependencies]
rand = "*"
