[package]
name = "ota-plus-client"
version = "0.1.0"
authors = ["Txus <txus@advancedtelematic.com>"]

[lib]
name = "libotaplus"
path = "src/lib.rs"

[[bin]]
name = "ota_plus_client"
path = "src/main.rs"
doc = false

[dependencies]
chan-signal = "0.1.5"
chan = "0.1.18"
env_logger = "0.3.3"
getopts = "0.2.14"
hyper = "0.8.1"
log = "0.3.5"
rustc-serialize = "0.3.18"
url = "0.5.9"
tempfile = "2.1.2"
toml = "0.1.28"
ws = "0.4.6"
yup-hyper-mock = "1.3.2"
