[package]
name = "ota-plus-client"
version = "0.1.0"
authors = ["Txus <txus@advancedtelematic.com>"]

[lib]
name = "libotaplus"
path = "src/lib.rs"

[[bin]]
name = "ota_plus_client"
path = "src/main.rs"
doc = false

[dependencies]
chan-signal = "*"
chan= "*"
env_logger = "*"
getopts = "*"
hyper = "*"
log = "*"
rustc-serialize = "*"
tempfile = "*"
toml = "*"
ws = "*"
