[package]
name = "ota-plus-client"
version = "0.1.0"
authors = ["Txus <txus@advancedtelematic.com>"]

[dependencies]
env_logger = "*"
hyper = "*"
log = "*"
rustc-serialize = "*"
toml = "*"
getopts = "*"