[package]
name = "ota-plus-client"
version = "0.1.0"
authors = ["Txus <txus@advancedtelematic.com>"]

[lib]
name = "libotaplus"
path = "src/lib.rs"

[[bin]]
name = "ota_plus_client"
path = "src/main.rs"
doc = false

[dependencies]
chan = "0.1.18"
chan-signal = "0.1.5"
crossbeam = "0.2.9"
env_logger = "0.3.3"
getopts = "0.2.14"
hyper = "0.9.6"
log = "0.3.5"
nom = "1.2.3"
rustc-serialize = "0.3.18"
tempfile = "2.1.2"
time = "0.1.35"
toml = "0.1.28"
url = "1.1.0"
ws = "0.4.6"
