[client]
storage_dir = "/var/sota"
rvi_url = "http://127.0.0.1:8901"
edge_url = "127.0.0.1:9080"
timeout = 20
vin_match = 2
http = true

[server]
server = "http://127.0.0.1:9000"
polling_interval = 10
vin = "V1234567890123456"
packages_dir = "/tmp/"
packages_extension = "deb"

[dbus]
name = "org.genivi.SotaClient"
path = "/org/genivi/SotaClient"
interface = "org.genivi.SotaClient"
software_manager = "org.genivi.SoftwareLoadingManager"
software_manager_path = "/org/genivi/SoftwareLoadingManager"
timeout = 60
