[auth]
server = "http://127.0.0.1:9000"
client_id = "client-id"
secret = "secret"
credentials_file = "/tmp/ats_credentials.toml"
vin = "V1234567890123456"

[ota]
server = "http://127.0.0.1:8080"
polling_interval = 10
packages_dir = "/tmp/"
package_manager = "dpkg"

[test]
http = false
repl = false
websocket = true
