[auth]
server = "http://127.0.0.1:9000"
client_id = "client-id"
secret = "secret"
credentials_file = "/tmp/ats_credentials.toml"

[device]
uuid = "123e4567-e89b-12d3-a456-426655440000"
vin = "V1234567890123456"

[gateway]
console = false
http = false
websocket = true

[ota]
server = "http://127.0.0.1:8080"
polling_interval = 10
packages_dir = "/tmp/"
package_manager = "dpkg"
