[client]
storage_dir = "/var/sota"
rvi_url = "http://127.0.0.1:8901"
edge_url = "127.0.0.1:9080"
timeout = 20
vin_match = 2

[dbus]
name = "org.genivi.sota_client"
path = "/org/genivi/sota_client"
interface = "org.genivi.sota_client"
software_manager = "org.genivi.software_loading_manager"
software_manager_path = "/org/genivi/software_loading_manager"
timeout = 60
