[client]
storage_dir = "/var/sota"
timeout = 20
vin_match = 2

[dbus]
name = "org.genivi.sota_client"
interface = "org.genivi.software_manager"
software_manager = "org.genivi.software_manager"
timeout = 60
